import { VehicleBody, SURFACES } from '../vehicle/physics.js';
import { clamp, clamp01, lerp, wrap } from '../core/math.js';
import { heatState } from '../stats/attributes.js';
import { chargesOf } from '../data/skills.js';

// A competitor: physics body + build + the three live resources.
//
// Player and rivals are the same class. That is not tidiness for its own sake —
// it means a rival is subject to the same collision maths, the same heat, and
// the same skill costs as the player, so "the AI is cheating" is structurally
// impossible. The only difference is who writes `input` each step.
//
// The three resources are the design brief's economy:
//   Durability — structural HP. Zero ends the run.
//   Energy     — pays for skills. Earned by drifting, kills, and regeneration.
//   Heat       — 0..100%. Generated by parts and skills, shed over time.
//                Crossing a threshold is an event other systems react to.

const MELTDOWN_DAMAGE_PER_SEC = 14;
// Nitrous economy. A full bottle is ~4.5 seconds of boost; a well-held drift
// pays for roughly half of what it costs to use, so the loop is drive-well ->
// spend, not hoard -> dump.
const NOS_DRAIN = 0.22;
const NOS_TRICKLE = 0.035;
const NOS_PER_DRIFT = 0.11;
const NOS_POWER = 0.34;
const NOS_NEAR_MISS = 0.09;

const MELTDOWN_DURATION = 2.4;

export class Racer {
  constructor({ build, isPlayer = false, name = 'Racer', archetype = null, colorSeed = 0 }) {
    this.build = build;
    this.isPlayer = isPlayer;
    this.name = name;
    this.archetype = archetype;
    this.colorSeed = colorSeed;

    this.body = new VehicleBody(build.physics);
    this.input = {
      throttle: 0, brake: 0, steer: 0, drift: false, nos: false,
      skills: [false, false, false, false],
    };

    const p = build.physics;
    this.maxDurability = p.maxDurability;
    this.durability = this.maxDurability;
    this.maxEnergy = p.maxEnergy;
    this.energy = this.maxEnergy * 0.5;

    // Nitrous, deliberately not Energy.
    //
    // Energy is the skill economy — spent on deck buttons, earned by playing
    // the build. Nitrous is the *driving* economy: earned by driving well and
    // spent on the straight after. Folding them together would mean every
    // squeeze of the bottle was a skill you did not cast, which is the wrong
    // decision to put in front of the player twenty times a lap.
    this.nos = 1;
    this.nosActive = false;
    this.heat = 0;                    // percent, 0..100
    this.heatStateId = 'normal';

    this.alive = true;
    this.finished = false;
    this.finishTime = 0;
    this.position = 1;                // race placing, 1-indexed

    // Progress. `lapProgress` is monotonic distance travelled around the
    // circuit; laps are counted by watching it wrap, not by a trigger volume,
    // so a car that clips the start line sideways cannot skip or double-count.
    this.lap = 0;
    this.trackS = 0;
    this._lastS = 0;
    this.totalDistance = 0;
    this.offTrackTime = 0;

    // Skill runtime state, one entry per equipped skill.
    this.cooldowns = build.skills.map(() => 0);
    // The magazine. Cooldowns pace a skill within a race; this is what stops
    // it being infinite over one — see `chargesOf`.
    this.charges = build.skills.map((sk) => chargesOf(sk, build.stats));
    this.meltdownTimer = 0;
    this.invulnTimer = 0;

    // Per-race telemetry, used by the results screen and the balance tool.
    this.stats = {
      drifted: 0, driftEnergy: 0, damageDealt: 0, damageTaken: 0,
      kills: 0, skillsUsed: 0, topSpeed: 0, timeAirborne: 0, offTrack: 0,
    };

    this.sample = {};
  }

  /** Re-read derived physics after the build changed between races. */
  refresh() {
    this.build.recompute();
    const p = this.build.physics;
    this.body.setPhysics(p);
    // Preserve the damage taken so far rather than the absolute value, so a
    // Durability upgrade mid-run does not silently heal the car.
    const frac = this.maxDurability > 0 ? this.durability / this.maxDurability : 1;
    this.maxDurability = p.maxDurability;
    this.durability = this.maxDurability * frac;
    this.maxEnergy = p.maxEnergy;
    this.energy = Math.min(this.energy, this.maxEnergy);
    this.cooldowns = this.build.skills.map((_, i) => this.cooldowns[i] ?? 0);
    // A skill swapped in mid-race arrives loaded; one already carried keeps
    // whatever it has left. Capped, because a part that grants charges can be
    // taken off as well as put on.
    this.charges = this.build.skills.map((sk, i) => {
      const full = chargesOf(sk, this.build.stats);
      return this.charges?.[i] === undefined ? full : Math.min(this.charges[i], full);
    });
  }

  placeAt(pose) {
    this.body.place(pose.x, pose.z, pose.yaw);
    this.body.y = pose.y ?? 0;
    this.trackS = pose.s ?? 0;
    this._lastS = this.trackS;
  }

  get durabilityFrac() { return clamp01(this.durability / Math.max(1, this.maxDurability)); }
  get energyFrac() { return clamp01(this.energy / Math.max(1, this.maxEnergy)); }

  get nosFrac() { return clamp01(this.nos); }

  /** Reward for threading a gap at speed. Traffic is what makes this pay. */
  awardNearMiss(strength = 1) {
    this.nos = Math.min(1, this.nos + NOS_NEAR_MISS * clamp01(strength));
    this.stats.nearMisses = (this.stats.nearMisses ?? 0) + 1;
  }
  get speedKmh() { return this.body.speed * 3.6; }

  // --- resources -----------------------------------------------------------

  /**
   * Put rounds back in the magazines.
   *
   * @param n  how many per skill; omitted refills them completely
   * @returns how many were actually loaded, across every skill
   */
  reloadSkills(n = Infinity) {
    let loaded = 0;
    this.charges = this.build.skills.map((sk, i) => {
      const full = chargesOf(sk, this.build.stats);
      const has = this.charges?.[i] ?? full;
      const now = Math.min(full, has + n);
      loaded += now - has;
      return now;
    });
    return loaded;
  }

  /** True while any skill still has a use left in it. */
  get anyCharges() { return (this.charges ?? []).some((c) => c > 0); }

  addEnergy(amount) {
    if (amount <= 0) return 0;
    const before = this.energy;
    this.energy = Math.min(this.maxEnergy, this.energy + amount);
    return this.energy - before;
  }

  spendEnergy(amount) {
    if (this.energy < amount) return false;
    this.energy -= amount;
    return true;
  }

  addHeat(amount) {
    if (amount === 0) return;
    // The Heat Capacity attribute scales what a unit of generated heat costs.
    const scaled = amount > 0 ? amount * this.build.physics.heatGainScale : amount;
    this.heat = clamp(this.heat + scaled, 0, 100);
  }

  /**
   * @returns actual damage applied, after armour and modifiers.
   */
  damage(amount, source = null, race = null) {
    if (!this.alive || amount <= 0) return 0;
    if (this.invulnTimer > 0) return 0;

    const p = this.build.physics;
    let dmg = amount * (1 - p.damageReduction) * this.build.stats.mod('damageTaken');

    const ctx = { amount: dmg, source, racer: this, race, cancelled: false };
    dmg = this.build.reduce('modifyDamageTaken', dmg, ctx);
    this.build.fire('onDamageTaken', { ...ctx, amount: dmg });
    if (ctx.cancelled) return 0;

    dmg = Math.max(0, dmg);
    this.durability -= dmg;
    this.stats.damageTaken += dmg;

    if (this.durability <= 0) {
      this.durability = 0;
      this.alive = false;
    }
    return dmg;
  }

  repair(amount) {
    if (amount <= 0) return 0;
    const before = this.durability;
    this.durability = Math.min(this.maxDurability, this.durability + amount);
    if (this.durability > 0) this.alive = true;
    return this.durability - before;
  }

  // --- per-step ------------------------------------------------------------

  /**
   * Advance resources. Motion is stepped separately by the race, because the
   * collision pass has to sit between the two.
   */
  stepResources(dt, race) {
    const p = this.build.physics;
    const body = this.body;

    // Energy: passive regeneration, plus the drift economy. This is the loop
    // the brief calls out by name — drive well, get resources, spend them on
    // skills, which is why Drift and Energy belong to the same build.
    this.addEnergy(p.energyRegen * dt);
    if (body.drifting && body.driftQuality > 0.05) {
      const gained = p.driftEnergyRate * body.driftQuality * dt;
      const actual = this.addEnergy(gained);
      // Gross, not net: a full tank would otherwise report a drift build as
      // earning nothing, which is the opposite of what it is doing.
      this.stats.driftEnergy += gained;
      this.stats.drifted += dt;
      this.build.fire('onDrift', {
        racer: this, race, dt, quality: body.driftQuality,
        slip: body.slipAngle, gained: actual,
      });
    }

    // Nitrous. Held, not tapped: the bottle drains while the button is down and
    // refills from driving, so it is a rhythm rather than a cooldown.
    //
    // Refilled by the things Underground rewards — holding a slide, and running
    // close to something at speed. Trickle regeneration on top so a clean,
    // cautious lap is never left with an empty bottle and nothing to do about
    // it, but slowly enough that it is not the main source.
    const wantNos = !!this.input.nos && this.nos > 0.02 && !this.finished;
    this.nosActive = wantNos;
    if (wantNos) {
      this.nos = Math.max(0, this.nos - NOS_DRAIN * dt);
      body.applyBoost(NOS_POWER, 0.12);
      this.stats.nosUsed = (this.stats.nosUsed ?? 0) + dt;
    } else {
      this.nos = Math.min(1, this.nos + NOS_TRICKLE * dt);
    }
    if (body.drifting && body.driftQuality > 0.05) {
      this.nos = Math.min(1, this.nos + NOS_PER_DRIFT * body.driftQuality * dt);
    }

    // Heat: passive generation from parts, cooling always, and extra cooling
    // from airflow so a fast car self-regulates a little.
    const airflow = 1 + clamp01(body.speed / Math.max(1, p.maxSpeed)) * 0.6;
    this.addHeat(this.build.stats.mod('heatGen') * dt);
    this.heat = Math.max(0, this.heat - p.heatCoolRate * airflow * dt);

    const st = heatState(this.heat);
    if (st.id !== this.heatStateId) {
      const from = this.heatStateId;
      this.heatStateId = st.id;
      this.build.fire('onHeatState', { racer: this, race, state: st.id, from });
      if (st.id === 'meltdown') this.meltdownTimer = MELTDOWN_DURATION;
    }

    // Meltdown: running at 100% heat costs Durability. Heat builds are meant
    // to live near this line, not past it.
    if (this.meltdownTimer > 0) {
      this.meltdownTimer -= dt;
      this.damage(MELTDOWN_DAMAGE_PER_SEC * dt, { type: 'meltdown' }, race);
      if (this.meltdownTimer <= 0) this.heat = Math.min(this.heat, 82);
    }

    // Hazard surfaces (lava) chew on you continuously.
    const surf = body.surface;
    if (surf && surf.damage > 0) {
      this.damage(surf.damage * dt, { type: 'surface', surface: surf.id }, race);
    }

    if (this.invulnTimer > 0) this.invulnTimer -= dt;
    for (let i = 0; i < this.cooldowns.length; i++) {
      if (this.cooldowns[i] > 0) this.cooldowns[i] -= dt;
    }

    // Telemetry
    if (this.speedKmh > this.stats.topSpeed) this.stats.topSpeed = this.speedKmh;
    if (body.airborne) this.stats.timeAirborne += dt;
    if (!this.sample.onTrack) {
      this.offTrackTime += dt;
      this.stats.offTrack += dt;
    } else {
      this.offTrackTime = 0;
    }

    this._raceTime = race?.time ?? 0;
    this.build.fire('onTick', { racer: this, race, dt });
  }

  /**
   * Why the car is not fully answering the controls, if it is not.
   *
   * Every one of these states already existed and every one of them felt
   * identical from the driving seat: you press throttle, brake and steering and
   * the car ignores you. Naming them on screen is the difference between a bug
   * report that says "it broke" and a player who knows they are spinning.
   *
   * Ordered by how completely each one takes control away.
   */
  controlState(loopStats = null, track = null) {
    const b = this.body;

    // Just repositioned by the stuck rescue.
    if (this.rescuedAt != null && this._raceTime != null
        && this._raceTime - this.rescuedAt < 2.0) {
      return { id: 'rescue', label: 'REPOSITIONED', why: 'you were stuck', severity: 0.6 };
    }

    if (b.stunTimer > 0) {
      return { id: 'stunned', label: 'SYSTEMS DOWN', why: 'EMP — no throttle, brake or steering', severity: 1 };
    }
    if (this.meltdownTimer > 0) {
      return { id: 'meltdown', label: 'MELTDOWN', why: 'venting heat and losing durability', severity: 1 };
    }

    // Sliding across your own direction of travel. Throttle and brake act on
    // the forward component, which has almost vanished, and the slip term has
    // saturated the steering — so nothing works, and nothing is broken.
    const slipDeg = Math.abs(b.slipAngle) * 57.3;
    if (b.speed > 12 && slipDeg > 55) {
      return {
        id: 'spin',
        label: b.drifting ? 'DRIFTING WIDE' : 'SPINNING',
        why: b.drifting
          ? 'release drift to regain grip'
          : 'counter-steer into the slide',
        severity: 1,
      };
    }

    // Punctured.
    //
    // Below the states that take the car away from you and above the ones that
    // are only awkward, because it is neither: the car answers perfectly, it
    // just will not go. That is exactly the failure this whole readout exists
    // for — a driver who cannot see it feels a slow car and blames the car.
    if (b.speedPenaltyTimer > 0) {
      return {
        id: 'punctured',
        label: 'PUNCTURED',
        why: `held to ${Math.round(b.speedPenalty * 100)}% — the pits can fix it`,
        severity: 0.6,
      };
    }

    // Only sustained flight is worth naming. A state that flickers on and off
    // as the car crests a rise is noise, and it was appearing constantly while
    // all four wheels were on the road.
    if (b.airborne && b.airTime > 0.2) {
      return { id: 'air', label: 'AIRBORNE', why: 'no traction until you land', severity: 0.6 };
    }

    // Nose-first into something with the throttle open and going nowhere.
    //
    // This used to read "slow and off the racing surface", which is a
    // description of driving on the verge — so it fired constantly, at
    // fifteen km/h on gravel with nothing holding the car at all, and told the
    // player to reverse out of a situation they were already driving through. A
    // warning that goes off while nothing is wrong is worse than no warning.
    // Now it waits for the car to actually refuse to move.
    if (b.stuckFor > 0.7) {
      return { id: 'wedged', label: 'WEDGED', why: 'hold S to reverse out', severity: 1 };
    }

    const surfGrip = b.surface?.grip ?? 1;
    if (b.gripPenalty < 0.75 || surfGrip < 0.5) {
      const cause = surfGrip < 0.5 ? (b.surface?.id ?? 'surface') : 'tyres upset';
      return { id: 'nogrip', label: 'NO GRIP', why: cause, severity: 0.6 };
    }

    // Facing the wrong way. Invisible before, and the single most recoverable
    // state there is — once you know that is what is happening.
    if (track && b.speed > 4) {
      const trackYaw = track.path.yawAt(this.trackS);
      const dy = Math.abs(((b.yaw - trackYaw + Math.PI * 3) % (Math.PI * 2)) - Math.PI);
      if (dy > 2.0) {
        return { id: 'wrongway', label: 'WRONG WAY', why: 'turn around', severity: 1 };
      }
    }

    if (!this.sample.onTrack) {
      return { id: 'off', label: 'OFF TRACK', why: b.surface?.id ?? 'rough', severity: 0.35 };
    }

    // The one that is genuinely the game's fault rather than the driver's.
    if (loopStats && loopStats.realtimeRatio < 0.9) {
      return {
        id: 'slowmo',
        label: 'RUNNING SLOW',
        why: `simulation at ${Math.round(loopStats.realtimeRatio * 100)}% of real time`,
        severity: 1,
      };
    }

    return null;
  }

  /**
   * Update lap counting from the track sample. Uses signed delta along the
   * closed path so it is immune to direction, position on the line, and the
   * seam at s = 0.
   */
  updateProgress(track) {
    const s = this.sample.s ?? 0;
    const delta = track.path.deltaAlong(this._lastS, s);
    // Ignore teleports (respawn) — anything larger than a plausible step.
    if (Math.abs(delta) < 60) {
      this.totalDistance += delta;
      // Crossing the start line forward increments the lap. Reversing over it
      // decrements, so a car spun around cannot farm laps by rocking back and
      // forth — but the count never goes below zero.
      const crossed = this._crossedLine(this._lastS, s, track.startS, delta);
      if (crossed > 0) this.lap++;
      else if (crossed < 0) this.lap = Math.max(0, this.lap - 1);
    }
    this._lastS = s;
    this.trackS = s;
  }

  _crossedLine(prev, now, line, delta) {
    if (delta === 0) return 0;
    // Did the interval [prev, now] — walked in the direction of `delta` —
    // contain `line`? Handles the seam at s = 0 in both directions.
    const forward = delta > 0;
    if (forward) {
      if (prev <= now) return (line > prev && line <= now) ? 1 : 0;
      return (line > prev || line <= now) ? 1 : 0;   // wrapped
    }
    if (prev >= now) return (line <= prev && line > now) ? -1 : 0;
    return (line <= prev || line > now) ? -1 : 0;
  }

  /**
   * Ranking key: laps completed, then distance around the current lap.
   *
   * Measured from the start line, not from raw `s`. The lap counter increments
   * when a car crosses the start line, but `s` wraps at the spline's seam — and
   * those are the same place only when `startS` happens to be 0. Otherwise the
   * seam sits mid-lap, and every car crossing it sees `s` fall from ~2047 to 0
   * while `lap` does not change: progress drops by a full lap length, ranking
   * scrambles, and the no-progress rescue starts firing every five seconds for
   * the rest of the lap.
   */
  raceProgress(track) {
    const rel = wrap(this.trackS - track.startS, track.length);
    return this.lap * track.length + rel;
  }
}
